import { z } from "zod";

export const specifyFormSchema = z.object({
  // Step 1: Patient
  isNewPatient: z.boolean().optional(),
  selectedPatientId: z.string().optional(),
  patientName: z.string().optional(),
  patientPhone: z.string().optional(),
  patientDob: z.string().optional(),
  patientGender: z.enum(["male", "female", "other"]).optional(),
  patientEmail: z.string().optional(),
  patientJob: z.string().optional(),
  patientContactName: z.string().optional(),
  patientContactPhone: z.string().optional(),
  patientAddress: z.string().optional(),

  // Step 2: Clinical
  patientHeight: z.union([z.number(), z.string()]).optional(),
  patientWeight: z.union([z.number(), z.string()]).optional(),
  patientHistory: z.string().optional(),
  familyHistory: z.string().optional(),
  medicalHistory: z.string().optional(),
  acuteDisease: z.string().optional(),
  chronicDisease: z.string().optional(),
  toxicExposure: z.string().optional(),
  medicalUsing: z.string().optional(),

  // Step 3: Service & Test
  serviceId: z.string().optional(),
  serviceType: z.enum(["reproduction", "embryo", "disease"]).optional(),
  genomeTestId: z.string().optional(),
  hospitalId: z.string().optional(),
  doctorId: z.string().optional(),
  samplingSite: z.string().optional(),
  sampleCollectDate: z.string().optional(),
  embryoNumber: z.union([z.number(), z.string()]).optional(),

  // Step 4: Genetic results
  geneticTestResults: z.string().optional(),
  geneticTestResultsRelationship: z.string().optional(),

  // Step 5: Service-specific (reproduction/embryo/disease)
  fetusesNumber: z.string().optional(),
  fetusesWeek: z.string().optional(),
  fetusesDay: z.string().optional(),
  ultrasoundDay: z.string().optional(),
  headRumpLength: z.string().optional(),
  neckLength: z.string().optional(),
  combinedTestResult: z.string().optional(),
  ultrasoundResult: z.string().optional(),
  biospy: z.string().optional(),
  biospyDate: z.string().optional(),
  cellContainingSolution: z.string().optional(),
  embryoCreate: z.string().optional(),
  embryoStatus: z.string().optional(),
  morphologicalAssessment: z.string().optional(),
  negativeControl: z.string().optional(),
  symptom: z.string().optional(),
  diagnose: z.string().optional(),
  testRelated: z.string().optional(),
  treatmentMethods: z.string().optional(),
  treatmentTimeDay: z.string().optional(),
  drugResistance: z.string().optional(),
  relapse: z.string().optional(),

  // Step 6: Note
  specifyNote: z.string().optional(),
  sendEmailPatient: z.boolean().optional(),

  // Edit mode: IDs for update (set when loading existing specify)
  patientClinicalId: z.string().optional(),
  reproductionServiceId: z.string().optional(),
  embryoServiceId: z.string().optional(),
  diseaseServiceId: z.string().optional(),
});

export type SpecifyFormData = z.infer<typeof specifyFormSchema>;

export const specifyFormDefaultValues: SpecifyFormData = {
  isNewPatient: true,
  selectedPatientId: "",
  patientName: "",
  patientPhone: "",
  patientDob: "",
  patientGender: undefined,
  patientEmail: "",
  patientJob: "",
  patientContactName: "",
  patientContactPhone: "",
  patientAddress: "",
  patientHeight: undefined,
  patientWeight: undefined,
  patientHistory: "",
  familyHistory: "",
  medicalHistory: "",
  acuteDisease: "",
  chronicDisease: "",
  toxicExposure: "",
  medicalUsing: "",
  serviceId: "",
  serviceType: undefined,
  genomeTestId: "",
  hospitalId: "",
  doctorId: "",
  samplingSite: "",
  sampleCollectDate: "",
  embryoNumber: undefined,
  geneticTestResults: "",
  geneticTestResultsRelationship: "",
  fetusesNumber: "",
  fetusesWeek: "",
  fetusesDay: "",
  ultrasoundDay: "",
  headRumpLength: "",
  neckLength: "",
  combinedTestResult: "",
  ultrasoundResult: "",
  biospy: "",
  biospyDate: "",
  cellContainingSolution: "",
  embryoCreate: "",
  embryoStatus: "",
  morphologicalAssessment: "",
  negativeControl: "",
  symptom: "",
  diagnose: "",
  testRelated: "",
  treatmentMethods: "",
  treatmentTimeDay: "",
  drugResistance: "",
  relapse: "",
  specifyNote: "",
  sendEmailPatient: false,
  patientClinicalId: "",
  reproductionServiceId: "",
  embryoServiceId: "",
  diseaseServiceId: "",
};
